repository:
  name: gcloud-aio
  description: (Asyncio OR Threadsafe) Google Cloud Client Library for Python
  homepage: https://github.com/talkiq/gcloud-aio/
  private: false

  has_issues: true
  has_projects: false
  has_wiki: true

  allow_merge_commit: false
  allow_rebase_merge: true
  allow_squash_merge: true

labels:
  - name: bug
    color: fc2929
  - name: feature
    color: 84b6eb
    oldname: enhancement
  - name: help wanted
    color: 159818
  - name: low-priority
    color: fbca04
  - name: task
    color: d93f0b
  - name: question
    color: cc317c
